[project]
name = 'high-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.NFT-trait-definition]
path = 'contracts/NFT-trait-definition.clar'
clarity_version = 2
epoch = 2.5

[contracts.Subscription-lifecycle]
path = 'contracts/Subscription-lifecycle.clar'
clarity_version = 2
epoch = 2.5

[contracts.tiered-NFT]
path = 'contracts/tiered-NFT.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
